name: Suggest an Enhancement
description: Propose a change to an existing feature or functionality
title: "CHN: "
labels: [ "change" ]
body:
- type: markdown
  attributes: 
    value: |
      Thanks for taking the time to propose a change - if you need any further assistance with the randomiser, please visit the [Cursed Words Thread](https://discord.com/channels/731205301247803413/1499176806962692196) in the Archipelago Discord Server.
- type: dropdown
  id: area
  attributes:
    label: Affected Area
    description: Please select the part of the project the change relates to
    options:
      - APWorld
      - Mod Client
      - Other
  validations:
    required: true
- type: markdown
  attributes: 
    value: |
      ---
      
      When proposing your change, please try to answer as many of the following questions as possible, where applicable:
      * What existing feature/functionality does the change relate to?
      * How does the change differ from the existing behaviour?
      * What benefit does the change bring and/or what problem does it solve?
      
      The more detail you can provide, the easier it is to understand, visualise and implement the change.
- type: textarea
  id: description
  attributes:
    label: Describe the change
    description: Provide a description of the change, including as much detail as possible
    placeholder: Enter your idea
  validations:
    required: true
- type: upload
  id: materials
  attributes:
    label: Upload Supporting Materials
    description: If you have any screenshots, drawings, diagrams etc. to help further explain the change, please provide them here
  validations:
    required: false
