blank_issues_enabled: false
contact_links:
- name: Cursed Words Archipelago Thread
  url: https://discord.com/channels/731205301247803413/1499176806962692196
  about: For any assistance with the randomizer, please visit this thread in the Archipelago Discord Server
